export const projects = [
  // {
  //   id: 6,
  //   name: "oak chalet",
  //   image1: "/projects/oak chalet 1.jpg",
  //   image2: "/projects/oak chalet 1.jpg",
  //   text: "",
  //   link: "",
  //   tech: ["React", "styled component", "tanstack query"],
  // },
  {
    id: 2,
    name: "fast pizza",
    image1: "/projects/fastpizza 1.jpg",
    image2: "/projects/fastpizza 2.jpg",
    text: "",
    link: "https://matrixfast-pizza.vercel.app/",
    tech: ["React", "Tailwindcss", "RTK", "Redux"],
  },
  {
    id: 3,
    name: "worldwise",
    image1: "/projects/worldwise 1.jpg",
    image2: "/projects/worldwise 2.jpg",
    text: "",
    link: "https://worldwise-six-iota.vercel.app/",
    tech: ["React", "JSON-server", "Leaflet"],
  },

  {
    id: 1,
    name: "shopsmart",
    image1: "/projects/shopsmart 1.jpg",
    image2: "/projects/shopsmart 2.jpg",
    text: "",
    link: "https://shopsmart-wine.vercel.app/",
    tech: ["React", "Tailwindcss"],
  },
  {
    id: 7,
    name: "savory sips",
    image1: "/projects/savory 1.jpg",
    image2: "/projects/savory 2.jpg",
    text: "",
    link: "https://stage3-task.vercel.app",
    tech: ["React", "Tailwindcss", "RTK"],
  },

  {
    id: 4,
    name: "mapty",
    image1: "/projects/mapty 1.jpg",
    image2: "/projects/mapty 2.jpg",
    text: "",
    link: "https://mapping-matrix.vercel.app/",
    tech: ["Html", "TailwindCss", "Javascript"],
  },
  {
    id: 5,
    name: "weather",
    image1: "/projects/weather 1.jpg",
    image2: "/projects/weather 2.jpg",
    text: "",
    link: "https://weather-app-psi-black.vercel.app/",
    tech: ["Html", "css", "js"],
  },
  // {
  //   id: 8,
  //   name: "product cart",
  //   image1: "/projects/weather 1.jpg",
  //   image2: "/projects/weather 2.jpg",
  //   text: "",
  //   link: "https://product-cart-iota.vercel.app",
  //   tech: ["react", "TailwindCss"],
  // },
];
